import type { NextPage } from "next";
import Head from "next/head";
import { ButtonLogin, Layout } from "components";
import styles from "../../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Kannibales SexShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main className={styles.main}>
          {session ? (
            <>
              <h1>Welcome {session.user?.email}</h1>
              <button onClick={() => signOut()}>Sign out</button>
            </>
          ) : (
            <ButtonLogin />
          )}
          <div>
            <h1 className={styles.title}>
              Tiendita <a href="https://nextjs.org">Kannibales</a>
            </h1>
          </div>
        </main>
      </Layout>
    </div>
  );
};

export default Home;
