import type { NextPage } from "next";
import Head from "next/head";
import { Layout, SignInModal } from "components";
import styles from "../../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Kannibales</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main className={styles.main}>
          {status === "unauthenticated" && <SignInModal />}

          <div>
            <h1 className={styles.title}>
              Tienda <a href="https://nextjs.org">Kannibales</a>
            </h1>
          </div>
        </main>
      </Layout>
    </div>
  );
};

export default Home;
